# echo Removing Market images ....
# sudo docker images -a | grep "gen4/market" | awk '{print $3}' | xargs sudo docker rmi
echo Building Market ...
sudo docker build -t gen4/market .
echo Tagging with the latest build number ...
sudo docker tag gen4/market gen4/market:mvp-${BUILD_NUMBER}
sudo docker tag gen4/market gen4/market:mvp-latest
echo Uploading to Docker Hub ...
sudo docker push gen4/market:mvp-${BUILD_NUMBER}
sudo docker push gen4/market:mvp-latest
